jobs:
  build-container:
    name: Build Docker container image
    runs-on: ubuntu-latest
    steps:
     - name: Publish to Docker GitHub
       uses: docker/build-push-action@v1
       with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: fubar7/DuckDnsUnraidv6
        tags: latest, $ {{ github.run_number }}
